config/routes.rb
Rails.application.routes.draw do

  root 'newspapers#index'
  Rails.application.routes.draw do
    resources :newspapers
    
    get 'category', to: 'category#index'
    get 'newspapers/show_by_cat/:id', to: 'newspapers#show_by_cat'
    get '/feedrss', to:'newspapers#feed_rss', :defaults => { :format => 'atom' }

    namespace :users do 
     get 'rolify', to: 'rolify#index'
     put 'rolify/add_role_to_user', to: 'rolify#role_to_user', as: 'add_role_to_user'
     delete 'remove_role_to_user/:user_name/:role_name', to: 'rolify#remove_role_to_user_button'
    end
    
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  end

end

app/models/newspaper.rb
class Newspaper < ActiveRecord::Base
	resourcify
	require 'twitter'

	def retrieveTweetFromAccountUCPCergy
		#return $client.search("from:UniversiteCergy", :result_type => "recent").take(200).collect do |tweet|
			#{}"#{tweet.user.screen_name}: #{tweet.text} #{tweet.created_at}"
					return $client.search("from:UniversiteCergy", :result_type => "recent").take(10).collect

	end
	def retrieveTweetFromAccountRPUCP
		return $client.search("from:rp_ucp", :result_type => "recent").take(10).collect
			#{}"#{tweet.user.screen_name}: #{tweet.text}"
	end
	def retrieveTweetFromAccountUCPAssoLide
		return $client.search("from:LIDEdeCergy", :result_type => "recent").take(10).collect
			#{}"#{tweet.user.screen_name}: #{tweet.text}"
	end
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  load_and_authorize_resource
  before_action :set_newspaper, only: [:show, :edit, :update, :destroy]
  skip_before_action :set_newspaper, only: [:feed_rss, :new, :create]


require 'rss'
require 'open-uri'

  # GET /newspapers
  # GET /newspapers.json
  def index
    @newspapers = Newspaper.all.order("created_at DESC")

    if $client != nil
      n = Newspaper.new
      @retrieveTweetFromAccountUCPCergy = n.retrieveTweetFromAccountUCPCergy
      @retrieveTweetFromAccountRPUCP = n.retrieveTweetFromAccountRPUCP
      @retrieveTweetFromAccountUCPAssoLide = n.retrieveTweetFromAccountUCPAssoLide
    end
    
    #display rss
    feed_url = "http://www.u-cergy.fr/_plugins/web/www/fr/filter/org.ametys.web.new.RSS.accueil/rss.xml"
    #@output = Array.new(10)
    open(feed_url) do |http|
      response = http.read
      @result = RSS::Parser.parse(response, false)
      #sort rss feed by desc
      @result.items.sort! { |x,y| y.pubDate <=> x.pubDate } 
    end
  end

  # GET /newspapers/1
  # GET /newspapers/1.json
  # Show the newspapers from the id parameter
  def show_by_cat
    @newspapers = Newspaper.where("id_categories = ?", params[:id])
  end

  # GET /newspapers/new
  def new
    @newspaper = Newspaper.new
  end

  # GET /newspapers/1/edit
  def edit
  end

  #GET /feedrss/
  def feed_rss
    @feednews = Newspaper.select("title, description, author,created_at, updated_at").order("updated_at DESC").all()
    respond_to do |format|
      format.html
        format.atom { render layout: false }
    end
  end

  # POST /newspapers
  # POST /newspapers.json
  def create
    @newspaper = Newspaper.new(newspaper_params)

    respond_to do |format|
      if @newspaper.save
        format.html { redirect_to @newspaper, notice: 'Newspaper was successfully created.' }
        format.json { render :show, status: :created, location: @newspaper }
      else
        format.html { render :new }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newspapers/1
  # PATCH/PUT /newspapers/1.json
  def update
    respond_to do |format|
      if @newspaper.update(newspaper_params)
        format.html { redirect_to @newspaper, notice: 'Newspaper was successfully updated.' }
        format.json { render :show, status: :ok, location: @newspaper }
      else
        format.html { render :edit }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newspapers/1
  # DELETE /newspapers/1.json
  def destroy
    @newspaper.destroy
    respond_to do |format|
      format.html { redirect_to newspapers_url, notice: 'Newspaper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newspaper
      @newspaper = Newspaper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newspaper_params
      params.require(:newspaper).permit(:title, :description, :author, :rating, :id_categories)
    end
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/views/newspapers/_form.html.erb
<%= form_for @newspaper, :html => { :class => "form-horizontal newspaper" } do |f| %>

    <% if @newspaper.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@newspaper.errors.count, "error") %> prohibited this newspaper from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @newspaper.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@newspaper[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@newspaper[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rating, :class => 'form-control' %>
    </div>
    <%= error_span(@newspaper[:rating]) %>
  </div>
  <div class="control-group">
    <%= f.label :author, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :author, :class => 'form-control' %>
    </div>
    <%= error_span(@newspaper[:author]) %>
  </div>
  <div class="control-group">
    <%= f.label :id_categories, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :id_categories, :class => 'form-control' %>
    </div>
    <%= error_span(@newspaper[:id_categories]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            newspapers_path, :class => 'btn btn-default' %>

<% end %>

app/views/newspapers/edit.html.erb
<%- model_class = Newspaper -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/newspapers/feed_rss.html.erb
<%= auto_discovery_link_tag(:atom, feedrss_url(format: "atom")) %>

app/views/newspapers/index.html.erb
<%- model_class = Newspaper -%>
<div class='une'><h1>A la une</h1></div>
 <% if can? :create, @newspaper %>
    <%= link_to t('Créer un article', :default => t("Créer un article")), new_newspaper_path, :class => 'btn btn-primary' %>
  <% end %>
<% @newspapers.each do |newspaper| %>
  <div class="bubble-news <%= newspaper.id_categories %>">
    <a class="bubble-title" href="<%= newspaper_path(newspaper)%>"><%= newspaper.title %></a>
    <span class="time"><%= newspaper.created_at.to_time.strftime('%d/%m/%y à %H:%M') %></span>
    <br>
    <p>
      <% if newspaper.description.length > 150 %>
      <% text = newspaper.description[0..150]+"..." %>
      <%= text %>
      <a href="<%= newspaper_path(newspaper)%>" class="readMore">Lire la suite</a>
      <% else %>
      <%= newspaper.description %>
      <% end %>
      </p>
      <% if can? :update, @newspaper %>
        <%= link_to t('Editer', :default => t("Editer")),edit_newspaper_path(newspaper), :class => 'btn btn-default btn-xs' %>
      <% end %>
      <% if can? :delete, @newspaper %>
        <%= link_to t('Supprimer', :default => t("Supprimer")),newspaper_path(newspaper),:method => :delete,:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Êtes vous sûr ?')) },:class => 'btn btn-xs btn-danger' %>
      <% end %>
  </div>
  <div class="coma-news"></div>
<% end %>

<div class='une'><h1>Derniers tweets</h1></div>
<% if $client != nil %>
  <% @retrieveTweetFromAccountUCPCergy.each do |tweet| %>
    <div class="bubble-twitter">
      <div class="bubble-title">@<%= tweet.user.screen_name %></div>
      <span class="time"><%= tweet.created_at.to_time.strftime('%d/%m/%y à %H:%M') %></span>
      <br><p><%= tweet.text %></p>
    </div>
    <div class="coma-twitter"></div>
  <% end %>

  <% @retrieveTweetFromAccountRPUCP.each do |tweet| %>
    <div class="bubble-twitter">
      <div class="bubble-title">@<%= tweet.user.screen_name %></div>
      <span class="time"><%= tweet.created_at.to_time.strftime('%d/%m/%y à %H:%M') %></span>
      <br><p><%= tweet.text %></p>
    </div>
    <div class="coma-twitter"></div>
  <% end %>


  <% @retrieveTweetFromAccountUCPAssoLide.each do |tweet| %>
    <div class="bubble-twitter">
      <div class="bubble-title">@<%= tweet.user.screen_name %></div>
      <span class="time"><%= tweet.created_at.to_time.strftime('%d/%m/%y à %H:%M') %></span>
      <br><p><%= tweet.text %></p>
    </div>
    <div class="coma-twitter"></div>
  <% end %>

  <div class='une'><h1>Les derniers flux RSS</h1></div>
<%= instance_variable_get(:@titleRss) %>
<% @result.items.each do |item| %>  
  <div class="bubble-rss">
    <a class="bubble-title" href="<%= item.link %>" target="_blank"><%= item.title %></a>
    <span class="time"><%= item.pubDate.to_time.strftime('%d/%m/%y à %H:%M') %></span>
    <br><p></p>
    <div class="coma-rss"></div>
  </div>
  
<% end %>


<% end %>

app/views/newspapers/new.html.erb
<%- model_class = Newspaper -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/newspapers/show.html.erb
<%- model_class = Newspaper -%>

<div class="bubble-news">
  <span class="bubble-title"><%= @newspaper.title %></span>
  <span class="bubble-time"><%= @newspaper.created_at.to_time.strftime('%d/%m/%y à %H:%M') %></span>
  <p><%= @newspaper.description %></p>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              newspapers_path, :class => 'btn btn-default'  %>

app/views/newspapers/show_by_cat.html.erb
<% @newspapers.each do |newspaper| %>
  <div class="bubble-news <%= newspaper.id_categories %>">
    <a class="bubble-title" href="<%= newspaper_path(newspaper)%>"><%= newspaper.title %></a>
    <span class="time"><%= newspaper.created_at.to_time.strftime('%d/%m/%y à %H:%M') %></span>
    <p>
      <% if newspaper.description.length > 150 %>
      <% text = newspaper.description[0..150]+"..." %>
      <%= text %>
      <a href="<%= newspaper_path(newspaper)%>" class="readMore">Lire la suite</a>
      <% else %>
      <%= newspaper.description %>
      <% end %>
      </p>
  </div>
  <div class="coma"></div>
<% end %>